controller_list:
- name: "scaled_pos_joint_traj_controller"
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - robot2_shoulder_pan_joint
    - robot2_shoulder_lift_joint
    - robot2_elbow_joint
    - robot2_wrist_1_joint
    - robot2_wrist_2_joint
    - robot2_wrist_3_joint
